export const lexicon: Record<string, number> = {
  // Positive words/phrases from gardening and summer texts
  blissful: 1.5,
  joyful: 1.5,
  rewarding: 1.5,
  happiness: 1.5,
  'positive vibe': 2.5,
  serene: 1,
  benefits: 1,
  'uplifts your mood': 2.5,
  'vibrant colors': 2,
  'enchanting fragrances': 2,
  'physical health': 1.5,
  'deep connection with nature': 2.5,
  'sense of satisfaction': 2,
  peace: 1.5,
  'golden rays': 2,
  vibrant: 1.5,
  'joyful moments': 2,
  'beauty of nature': 2,
  warmth: 1,
  brightness: 1,
  'beautiful summer mornings': 2.5,
  'bright morning': 1.5,
  'chorus of birds': 1.5,
  'fresh scent': 1.5,
  'delightful weather': 2,
  magnificent: 1.5,
  'golden sunsets': 2,
  'pleasant breeze': 1.5,
  'time of wonder': 2,
  cherish: 1.5,
  'joyful heart': 2,

  // Neutral words/phrases from art text
  'modern art': 0.2, // A slight positive bias since art is often considered positively.
  'neither good nor bad': 0,
  'vast and diverse': 0,
  'without the lenses of prejudice': 0,
  'different perspectives': 0,
  'open mind': 0.2, // Being open-minded is slightly positive.
  essence: 0,
  'provoke thought': 0.2, // Provoking thought is considered slightly positive.
  'challenge established norms': 0.2, // Challenging norms can be considered slightly positive.
  'new and different perspectives': 0.5, // Encouraging new perspectives is positive.
  'neither seeks approval nor disapproval': 0,
  'standing firm': 0,

  // Negative words/phrases from urban living and junk food texts
  challenges: -1.5,
  'not-so-rosy': -2,
  'noise pollution': -2.5,
  distress: -2,
  'high cost of living': -2.5,
  'hefty price tag': -2,
  'expensive amenities': -2,
  pollution: -2,
  'negatively affect': -2.5,
  downside: -1.5,
  'junk food': -2,
  'negative effects': -2.5,
  'health concerns': -2,
  obesity: -2,
  'heart disease': -2.5,
  diabetes: -2,
  'high levels of sugar': -2,
  'unhealthy fats': -2,
  'environmental impact': -1.5,
  'pollution and waste': -2,
  'harming our planet': -2.5,
};

export const stopwords: Set<string> = new Set([
  'a',
  'about',
  'above',
  'after',
  'again',
  'against',
  'all',
  'am',
  'an',
  'and',
  'any',
  'are',
  "aren't",
  'as',
  'at',
  'be',
  'because',
  'been',
  'before',
  'being',
  'below',
  'between',
  'both',
  'but',
  'by',
  "can't",
  'cannot',
  'could',
  "couldn't",
  'did',
  "didn't",
  'do',
  'does',
  "doesn't",
  'doing',
  "don't",
  'down',
  'during',
  'each',
  'few',
  'for',
  'from',
  'further',
  'had',
  "hadn't",
  'has',
  "hasn't",
  'have',
  "haven't",
  'having',
  'he',
  "he'd",
  "he'll",
  "he's",
  'her',
  'here',
  "here's",
  'hers',
  'herself',
  'him',
  'himself',
  'his',
  'how',
  "how's",
  'i',
  "i'd",
  "i'll",
  "i'm",
  "i've",
  'if',
  'in',
  'into',
  'is',
  "isn't",
  'it',
  "it's",
  'its',
  'itself',
  "let's",
  'me',
  'more',
  'most',
  "mustn't",
  'my',
  'myself',
  'no',
  'nor',
  'not',
  'of',
  'off',
  'on',
  'once',
  'only',
  'or',
  'other',
  'ought',
  'our',
  'ours',
  'ourselves',
  'out',
  'over',
  'own',
  'same',
  "shan't",
  'she',
  "she'd",
  "she'll",
  "she's",
  'should',
  "shouldn't",
  'so',
  'some',
  'such',
  'than',
  'that',
  "that's",
  'the',
  'their',
  'theirs',
  'them',
  'themselves',
  'then',
  'there',
  "there's",
  'these',
  'they',
  "they'd",
  "they'll",
  "they're",
  "they've",
  'this',
  'those',
  'through',
  'to',
  'too',
  'under',
  'until',
  'up',
  'very',
  'was',
  "wasn't",
  'we',
  "we'd",
  "we'll",
  "we're",
  "we've",
  'were',
  "weren't",
  'what',
  "what's",
  'when',
  "when's",
  'where',
  "where's",
  'which',
  'while',
  'who',
  "who's",
  'whom',
  'why',
  "why's",
  'with',
  "won't",
  'would',
  "wouldn't",
  'you',
  "you'd",
  "you'll",
  "you're",
  "you've",
  'your',
  'yours',
  'yourself',
  'yourselves',
]);
